# Generated by Django 4.1 on 2022-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("url", models.CharField(max_length=200)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "article",},
        ),
    ]
