# Generated by Django 4.1 on 2022-08-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag_category"),
    ]

    operations = [
        migrations.AlterModelTable(name="category", table="category",),
        migrations.AlterModelTable(name="tag", table="tag",),
    ]
