# Generated by Django 4.1 on 2022-08-16 04:54

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_table_alter_tag_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="text", field=mdeditor.fields.MDTextField(),
        ),
    ]
